### ISSUE TITLE
meta.retrieval fails to find an genome that has a RefSeq genome

### ISSUE THREAD

**Issue by clementfkent** [ropensci/biomartr#110]
call:
meta.retrieval(kingdom = "invertebrate", db = "refseq", type = "CDS", reference=TRUE, path="/Volumes/LaCie4TB/RefSeq")
# downloaded 13 species correctly, then fails:
----------> No reference genome or representative genome was found for 'Aplysia californica'. Thus, download for this species has been omitted. Have you tried to specify getGenome(db = 'refseq', organism = 'Aplysia californica' , reference = FALSE) ? Alternatively, you can retrieve genome assemblies using the NCBI accession ID or NCBI Taxonomy ID. See '?'is.genome.available' for examples.
Error in assembly$ftp_path : $ operator is invalid for atomic vectors

 is.genome.available(org="Aplysia californica")
A reference or representative genome assembly is available for 'Aplysia californica'.
More than one entry was found for 'Aplysia californica'. Please consider to run the function 'is.genome.available()' and specify 'is.genome.available(organism = Aplysia californica, db = refseq, details = TRUE)'. This will allow you to select the 'assembly_accession' identifier that can then be specified in all get*() functions.

MacBook M1 Pro, Monterey 12.7.3, R 4.3.2 GUI 1.80 Big Sur ARM build (8281)
Biomart and biomartr and dependencies freshly installed.

**Comment by HajkD** [comment]
Hi,

The function stops, because `reference = TRUE` is enforced but no reference genome is available. I will have a look into skipping the species for which no reference genome is available. For now simply setting `reference=FALSE` should solve your retrieval issue.

I hope this helps.

Best,
Hajk

**Comment by clementfkent** [comment]
Thanks!
