### ISSUE TITLE
issue with download from NCBI refseq/genebank

### ISSUE THREAD

**Issue by Li-Yuanshuo** [ropensci/biomartr#116]
Hi, thank you for your effort on developing this R package.

But it seems NCBI has change their ftp address from  _ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/_ to  
_~~ftp://~~ ftp.ncbi.nlm.nih.gov/genomes/refseq/_
So all functions that get data from NCBI shows timeout. But Ensembl are working.

Could you please check and update the address?

Thank you.

**Comment by HajkD** [comment]
Hi @Li-Yuanshuo 

Thank you so much for making me aware of this.

@Roleren Would you by any chance have some time to look into this?

With many thanks and very best wishes,
Hajk

**Comment by Roleren** [comment]
Sure, easy fix, will push it tomorrow morning
