### ISSUE TITLE
Retrieval of different ENSEMBL and NCBI versions

### ISSUE THREAD

**Issue by HajkD** [ropensci/biomartr#13]
Ge Tan suggested:

>Dear Dr Hajk-Georg Drost,
> 
>Thanks for crating this useful package, which saves significant amount of work for us.
>
>One more feature that would be useful for us is the option to download GTF from Ensembl.
>Currently only the GFF3 file is supported.
>
>Is it possible for you to add this new feature for us?
> 
>In further, it will also be nice to able to select the release version of Ensembl.
> 
>Let me know what you think.
> 
>Many thanks,
>Ge

I already implemented the new function `getGTF()` (can be used when downloading the developer version of `biomartr`) and I put the version option for ENSEMBL and NCBI on my TODO list. This option will be coming soon :)

Thank you so much for this great suggestion Ge!

**Comment by Roleren** [comment]
This is now fixed and work for all kingdoms in ensembl, using the format specification:
```

getGTF( db       = "ensembl",
          organism = "Saccharomyces cerevisiae",
          path = tempdir(), mute_citation = TRUE)
```
or equally with format specification:

```
getGFF( db       = "ensembl",
          organism = "Saccharomyces cerevisiae",
          path = tempdir(), mute_citation = TRUE, format = "gtf")
```

This issue can now be closed.

**Comment by HajkD** [comment]
Wonderful, thank you so much @Roleren! :)
