### ISSUE TITLE
Please use git tags and releases

### ISSUE THREAD

**Issue by sckott** [ropensci/biomartr#17]
hi 👋  

We want all rOpenSci pkgs to consistently keep track of changes. You already use NEWS.md, thanks for that. Please also do the following:

- git tag each CRAN version, to git tag commits for previous CRAN versions, you can find the commit, then do e.g., `git tag -a v1.2 9fceb02` where `9fceb02` is the commit sha
- use the [releases tab](https://github.com/ropensci/biomartr/releases) in this repo to include the associated NEWS items for each tag/version, e.g., see https://github.com/ropensci/taxize/releases/tag/v0.8.8

Can you please do the two above items from now on?

**Comment by HajkD** [comment]
Hi @sckott 

Many thanks for getting in touch with me.

I tagged the latest CRAN version now and also created a release tab.

Best wishes,
Hajk

**Comment by sckott** [comment]
Thanks, and do put in NEWS items in the release tag when you send to CRAN

bonus points for referring to specific issues when applicable like `(#14)` but you don't have to do that

**Comment by sckott** [comment]
can you use release notes for your NEWS items for each CRAN release? looks like they are missing for the latest CRAN release https://github.com/ropensci/biomartr/releases

**Comment by HajkD** [comment]
I am so sorry! I completely forgot. I now added the new release and also included it in the NEWS file. Many thanks for making me aware of this!

**Comment by sckott** [comment]
thanks
