### ISSUE TITLE
requesting some info for JSON-LD metadata

### ISSUE THREAD

**Issue by chrisfan24** [ropensci/biomartr#18]
👋  @HajkD I'm using codemetar to create JSON-LD metadata for rOpenSci packages. I'd like some info about biomartr when you have the time, since you're the author / maintainer. In particular, I need your ORCID identifier as well as some keywords for the package that would help for search. 

Thanks and let me know if you need me to elaborate on what I'm doing!

**Comment by HajkD** [comment]
Hi @chrisfan24 

That's a great idea! Thank you very much for setting up such as a useful system. I am more than happy to help.

My ORCID: 0000-0002-1567-306X
Keywords: BioMart, genomic data retrieval, annotation retrieval, database retrieval, NCBI, ENSEMBL, biological data retrieval

I hope this helps :-)

Cheers, 
Hajk
