### ISSUE TITLE
get groups() doesn't provide information for database ensemblgenomes

### ISSUE THREAD

**Issue by anilsakshi** [ropensci/biomartr#30]
getGroups(db = "ensemblgenomes", kingdom = "EnsemblProtists")

Here is the error:-

Error in listGroups(db = db, kingdom = kingdom, details = FALSE) : 
  Unfortunately, only db = 'refseq' and db = 'genbank' 
                 provide group information.

Please reply for this issue.

Thanks!

**Comment by HajkD** [comment]
Hi @anilsakshi 

Unfortunately, the ENSEMBL or ENSEMBLGENOMES databases don't provide information about subgroups or domains of taxa/species. Thus, the feature of retrieving taxonomic `group` information is limited to the databases `RefSeq` and `Genbank` as stated in the error message.

In the future, I will try to incorporate taxonomic databases in the `biomartr` retrieval process,
but this will require quite some developer effort, so this feature will be available only in a while.

I hope this helps.

Cheers,
Hajk
