### ISSUE TITLE
Specify Ensembl Plant version

### ISSUE THREAD

**Issue by timedreamer** [ropensci/biomartr#31]
Hello,
 Really great package. It's now part of my working flow for all analysis. I'm working with plants, so I use [Ensembl Plant](https://plants.ensembl.org/index.html) a lot. One thing I'm curious is: is there any way to specify the release version of *Ensembl Plant*?

 Similar with Ensembl, Ensembl Plant also updates regularly. I want to keep my result replicable, in case they update their database. For example, in the newest Release 40, the *Setaria italica* genome was updated. It seems they do have several *archived* sites, like [Release 35](http://mar2016-plants.ensembl.org/index.html) and [Release 37](http://oct2017-plants.ensembl.org/index.html).

 An example of my code to retrieve gene description is below. It would be awesome if the version info could be implemented (maybe it's already done?) 

 ```R
biomart(genes = gene_list),
        mart = "plants_mart",
        dataset = "zmays_eg_gene",
        attributes = c("description",
                       "external_gene_name", "external_gene_source"),
        filters = "ensembl_gene_id")
```

 Thank you!!

Best,
Ji

**Comment by HajkD** [comment]
Hi Ji,

I am very happy that `biomartr` is useful for your research and thank you very much for
making such a great suggestion.

I will gladly implement a new argument `release` in the `biomart()` function (as well as in all `get*()`) functions to make it even easier to reproducibly retrieve data from different releases.

I will keep you posted here and will write you as soon as I have the new functionality embedded in the new `biomartr` version.

Many many thanks for your great feedback! I truly appreciate it :)

Cheer,s
Hajk

**Comment by timedreamer** [comment]
Hi Hajk,
 Just wonder whether there is any updates on the ensembl `version` functionality?

Best,
Ji

**Comment by Roleren** [comment]
See discussion:

https://github.com/ropensci/biomartr/issues/45

So @HajkD , will the new PR, solve this issue too ?

**Comment by HajkD** [comment]
Yes absolutely! Thanks to your pr this is now resolved. @timedreamer please let us know if it works for you?

**Comment by HajkD** [comment]
I assume this has been solved.
