### ISSUE TITLE
Adding a section "similar work" to README

### ISSUE THREAD

**Issue by sinarueeger** [ropensci/biomartr#32]
I think it would be useful to have a section in the README file that compares biomartr to similar work, most importantly [biomaRt](https://bioconductor.org/packages/release/bioc/html/biomaRt.html). 

It would help the user understand the differences between these two packages with almost identical names. 

I came across a section like this in the [drake package](https://github.com/ropensci/drake#similar-work).

**Comment by sinarueeger** [comment]
Hi Hajk

I did know that there was a FAQ file, should have checked. Those are some good explanations, thank you!

You could have a very short README section dedicated to `similar work` where you refer to issue #11 and the FAQs.

Best wishes
Sina

**Comment by HajkD** [comment]
Hi Sina,

Perfect. I now added the new section to the `README` so that future users will have a better chance to learn the differences between the packages.

Once more thank you very much for your suggestion and I always welcome feedback :))))

Cheers,
Hajk

**Comment by sinarueeger** [comment]
Great - thanks for adding this!
