### ISSUE TITLE
Error in curl::curl_fetch_memory("www.google.com") 

### ISSUE THREAD

**Issue by SepOrion** [ropensci/biomartr#35]
Hello,
    I am a student from China. When i use "listKingdoms()" and "getGenome()", i did not meet any problem, it successfully completed the download. However, when i use meta.retrieval(kingdom = "vertebrate_mammalian",db = "refseq",type = "genome"), it produced a error : 
Error in curl::curl_fetch_memory("www.google.com") : 
  Recv failure: Connection reset by peer

How do I solve this problem? 

Thank you very much
Best,
Liu

**Comment by SepOrion** [comment]
when use  download.database(db = "nr.27.tar.gz")  i meet the same problem
Error in curl::curl_fetch_memory("www.google.com") : 
  Recv failure: Connection reset by peer

**Comment by SepOrion** [comment]
> meta.retrieval(kingdom = "EnsemblBacteria", db = "ensembl", type = "genome")
Error in curl::curl_fetch_memory("www.google.com") : 
  Recv failure: Connection reset by peer

**Comment by HajkD** [comment]
Hi Liu,

Many thanks for contacting me. Could it be that google access is restricted in China?

If yes, could you please send me an url that isn't restricted so that I can exchange it.
I am basically testing with this function if a user has internet access or not since I experienced users that run `biomartr` without having internet access.

I hope this helps.

Cheers,
Hajk

**Comment by SepOrion** [comment]
Thank you for your reply. In my linux, i cannot to google. In my windows，i can connect the google, but it has the same question. (Error in curl::curl_fetch_memory("www.google.com")

"cn.bing.com"  isn't restricted.

Thank you very much
Best,
Liu

**Comment by SepOrion** [comment]
After I modified R code, i download 9 bacetria reference sequence, but then my  server has been banned by NCBI. Now i cannot connect to NCBI. Even use wget. How can i resolve it.

`[lcl@localhost lcl]$ wget ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/assembly_summary.txt
--2018-11-17 12:25:13--  http://ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/assembly_summary.txt
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... failed: Name or service not known.
wget: unable to resolve host address ‘ftp.ncbi.nlm.nih.gov’
[lcl@localhost lcl]$ wget ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/assembly_summary.txt
--2018-11-17 12:25:28--  http://ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/assembly_summary.txt
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... failed: Name or service not known.
wget: unable to resolve host address ‘ftp.ncbi.nlm.nih.gov’
[lcl@localhost lcl]$ wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/270/005/GCA_000270005.1_ASM27000v1/GCA_000270005.1_ASM27000v1_protein.faa.gz
--2018-11-17 12:27:40--  ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/270/005/GCA_000270005.1_ASM27000v1/GCA_000270005.1_ASM27000v1_protein.faa.gz
           => ‘GCA_000270005.1_ASM27000v1_protein.faa.gz’
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... failed: Name or service not known.
wget: unable to resolve host address ‘ftp.ncbi.nlm.nih.gov`

**Comment by HajkD** [comment]
Hi Liu,

To be honest, I have no idea why you are being banned. 

Your case is the first one I heard someone complaining about being banned from NCBI.

I tried to do some googling to find out more, but obviously, there is not much information out there why and to what extend server access to NCBI is banned from China. 

I am very sorry that I cannot help more on this matter. Maybe you could contact the NCBI Helpdesk to find out more?

Best wishes,
Hajk
