### ISSUE TITLE
Error when downloading multiple CDS files (not meta.retrieval)

### ISSUE THREAD

**Issue by eggrandio** [ropensci/biomartr#39]
Hi,

I am trying to download several CDS files from genbank, but I am not getting all of them because some species do not have a CDS file, however, the getCDS command acts as if they were downloaded.

I am using lappy to pass a list of species using their taxonids to getCDS. I first checked that these species have a genome assembly using the assembly_summary.txt file. I think that most of them do not have a CDS file, although there is a genomic assembly, and that is where the problem lies.

`lapply(assembly.monocot.genbank, getCDS, db="genbank", reference =F, path = file.path("_ncbi_downloads","monocot","CDS_genbank"))`

For most of the species, I get the CDS fasta file:

> Starting CDS retrieval of '1504633' from genbank ...
|=============================================================================================================================| 100%   64 MB
CDS download of 1504633 is completed!
Checking md5 hash of file: _ncbi_downloads/monocot/CDS_genbank/1504633_md5checksums.txt ...
The md5 hash of file '_ncbi_downloads/monocot/CDS_genbank/1504633_md5checksums.txt' matches!
The genomic CDS of '1504633' has been downloaded to '_ncbi_downloads/monocot/CDS_genbank' and has been named '1504633_cds_from_genomic_genbank.fna.gz' .

But for some others I get the message:

> Starting CDS retrieval of '1148796' from genbank ...
|=============================================================================================================================| 100%   64 MB
The genomic CDS of '1148796' has been downloaded to '_ncbi_downloads/monocot/CDS_genbank' and has been named '1148796_cds_from_genomic_genbank.fna.gz' .

And there is no fasta file to be found. However, `doc_1148796_db_genbank.txt` and `doc_1148796_db_genbank.tsv` files are in the folder.

Is there a way of checking if a species has a CDS file available?

As a result of using lapply I get a list at the end for all the species:

> [[1]]
[1] "_ncbi_downloads/monocot/CDS_genbank/2003741_cds_from_genomic_genbank.fna.gz"
[[2]]
[1] "_ncbi_downloads/monocot/CDS_genbank/1736659_cds_from_genomic_genbank.fna.gz"
[[3]]
[1] "_ncbi_downloads/monocot/CDS_genbank/1504633_cds_from_genomic_genbank.fna.gz"

When I check the warnings() after the command ends I can see this:

> Warning messages:
1: The download session seems to have timed out at the FTP site 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/002/966/915/GCA_002966915.1_ASM296691v1/GCA_002966915.1_ASM296691v1_cds_from_genomic.fna.gz'. This could be due to an overload of queries to the databases. Please restart this function to continue the data retrieval process or wait for a while before restarting this function in case your IP address was logged due to an query overload on the server side.
2: The download session seems to have timed out at the FTP site 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/952/365/GCA_001952365.1_ASM195236v1/GCA_001952365.1_ASM195236v1_cds_from_genomic.fna.gz'. This could be due to an overload of queries to the databases. Please restart this function to continue the data retrieval process or wait for a while before restarting this function in case your IP address was logged due to an query overload on the server side.
3: The download session seems to have timed out at the FTP site 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/182/835/GCA_001182835.1_Oropetium_genomic_20141112/GCA_001182835.1_Oropetium_genomic_20141112_cds_from_genomic.fna.gz'. This could be due to an overload of queries to the databases. Please restart this function to continue the data retrieval process or wait for a while before restarting this function in case your IP address was logged due to an query overload on the server side.

When I check the `ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/002/966/915/GCA_002966915.1_ASM296691v1/` folder for example, I see that there is no cds file there and I think that is the reason of why I am not getting them, they don't exist! but the getCDS command is not checking correctly if they do, so it gives the message as if they were downloaded.

I know sometimes NCBI blocks connections that do many queries, so maybe some of these files do exist, but if I run the command again, it tries to download all of them again.

I hope my problem is clearly explained and I hope it is easy to fix too, I find this tool really useful for what I want to do, and it has saved me a lot of time even with this error!

Thanks!

PS: I have also used the meta.retrieval command to get CDS from RefSeq ("Land plants"), but I cannot use it for genbank queries.

**Comment by eggrandio** [comment]
Going through previous issues I have found that you added this functionality before. However, it is not being used in getCDS (it's after #).

Why has it been removed? did it give any problems?

` # if (!exists.ftp.file(url = paste0(FoundOrganism$ftp_path, "/"),
                #                      file.path = download_url)) {
                #     message(
                #     "Unfortunately no CDS file could be found for organism '",
                #         organism,
                #     "'. Thus, the download of this organism has been omitted."
                #     )
                #     return(FALSE)
                # }`

**Comment by HajkD** [comment]
Hi @eggrandio 

The new (developer version) of `biomartr` now picks up where it left off when re-running `meta.retrieval()`.

Also could the default timeout limit of 60s explain this issue?

You can reset the timeout limit via:

```r
options(timeout = 3000000)
```

If you now install the developer version of `biomartr`, the timeout limit is now internally handled by default. 


I hope this helps?

Cheers,
Hajk
