### ISSUE TITLE
the library cannot properly handle "Heterocephalus glaber female"

### ISSUE THREAD

**Issue by antonkulaga** [ropensci/biomartr#43]
There are two genomes (and thus two reference species) for "Heterocephalus glaber" in Ensembl. Unfortunately it is impossible to get them from any of:
```R
biomartr::organismBM(organism = "Heterocephalus glaber female")
biomartr::organismBM(organism = "Heterocephalus glaber male")
biomartr::organismBM(organism = "Heterocephalus glaber")
```

**Comment by HajkD** [comment]
Hi Anton,

Many thanks for contacting me.

I just checked whether `Heterocephalus glaber` is available in BioMart and it seems that BioMart doesn't provide any species information for this species. 

```r
# install.packages(c("dplyr", "stringr", "biomartr"))
test <- biomartr::organismBM()
dplyr::filter(test, stringr::str_detect(organism_name, "glaber"))
```
```
 organism_name description                     mart      dataset    version   
  <chr>         <chr>                           <chr>     <chr>      <chr>     
1 oglaberrima   Oryza glaberrima genes (Oryza_… plants_m… oglaberri… Oryza_gla…
2 oglaberrima   Oryza glaberrima Short Variant… plants_v… oglaberri… Oryza_gla…
```

It seems like the only available species that includes `glaber` in its name is `Oryza glaberrima`..

Would it be possible to be more specific in case there is still something missing and it is in principle possible to retrieve information for  `Heterocephalus glaber` from BioMart?

Many thanks,
Hajk

**Comment by antonkulaga** [comment]
In Biomart there are two datasets for  Heterocephalus glaber:
hmale_gene_ensembl and hfemale_gene_ensembl

**Comment by HajkD** [comment]
Thanks for clarifying. This means the scientific name convention was violated. Since `H male` and `H female` is not a scientific name.

Anyway, this will work in that case:

```r
biomartr::organismBM("H male")
```

```
# A tibble: 2 x 5
  organism_name description                mart          dataset       version 
  <chr>         <chr>                      <chr>         <chr>         <chr>   
1 hmale         Naked mole-rat male genes… ENSEMBL_MART… hmale_gene_e… HetGla_…
2 hmale         Naked mole-rat male seque… ENSEMBL_MART… hmale_genomi… HetGla_…
```
and

```r
biomartr::organismBM("H female")
```

```
# A tibble: 2 x 5
  organism_name description                mart        dataset       version   
  <chr>         <chr>                      <chr>       <chr>         <chr>     
1 hfemale       Naked mole-rat female gen… ENSEMBL_MA… hfemale_gene… HetGla_fe…
2 hfemale       Naked mole-rat female seq… ENSEMBL_MA… hfemale_geno… HetGla_fe…
```

I hope this solves the issue?

Many thanks,
Hajk
