### ISSUE TITLE
How to download GRCh37 data?

### ISSUE THREAD

**Issue by ShixiangWang** [ropensci/biomartr#45]
Dear author,

I want to download the GRCh37 protein sequence, is it possible?

```
HS.proteome.refseq <- getProteome( db       = "emsembl", 
                                   organism = "Homo sapiens",
                                   path     = file.path("_ncbi_downloads","proteomes"))
```

Best,
Shixiang

**Comment by ShixiangWang** [comment]
I find out there is a `release` option, but it does not work

```
> biomartr::getReleases(db = "ensembl")
The current ENSEMBL release is release-97.
 [1] "release-1"  "release-2"  "release-3"  "release-4"  "release-5"  "release-6"  "release-7" 
 [8] "release-8"  "release-9"  "release-10" "release-11" "release-12" "release-13" "release-14"
[15] "release-15" "release-16" "release-17" "release-18" "release-19" "release-20" "release-21"
[22] "release-22" "release-23" "release-24" "release-25" "release-26" "release-27" "release-28"
[29] "release-29" "release-30" "release-31" "release-32" "release-33" "release-34" "release-35"
[36] "release-36" "release-37" "release-38" "release-39" "release-40" "release-41" "release-42"
[43] "release-43" "release-44" "release-45" "release-46" "release-47" "release-48" "release-49"
[50] "release-50" "release-51" "release-52" "release-53" "release-54" "release-55" "release-56"
[57] "release-57" "release-58" "release-59" "release-60" "release-61" "release-62" "release-63"
[64] "release-64" "release-65" "release-66" "release-67" "release-68" "release-69" "release-70"
[71] "release-71" "release-72" "release-73" "release-74" "release-75" "release-76" "release-77"
[78] "release-78" "release-79" "release-80" "release-81" "release-82" "release-83" "release-84"
[85] "release-85" "release-86" "release-87" "release-88" "release-89" "release-90" "release-91"
[92] "release-92" "release-93" "release-94" "release-95" "release-96" "release-97"
> HS.proteome.refseq <- getProteome( db       = "ensembl", 
+                                    organism = "Homo sapiens",
+                                    path     = "proteomes", 
+                                    release =  "release-75", 
+                                    gunzip = TRUE)
Starting proteome retrieval of 'Homo sapiens' from ensembl ...


错误: Please provide a release number that is supported by ENSEMBL.
> HS.proteome.refseq <- getProteome( db       = "ensembl", 
+                                    organism = "Homo sapiens",
+                                    path     = "proteomes", 
+                                    release =  "75", 
+                                    gunzip = TRUE)
Starting proteome retrieval of 'Homo sapiens' from ensembl ...


Error in curl::curl_fetch_memory(url) : Given file does not exist
> HS.proteome.refseq <- getProteome( db       = "ensembl", 
+                                    organism = "Homo sapiens",
+                                    path     = "proteomes", 
+                                    release =  "v75", 
+                                    gunzip = TRUE)
Starting proteome retrieval of 'Homo sapiens' from ensembl ...


错误: Please provide a release number that is supported by ENSEMBL.
> HS.proteome.refseq <- getProteome( db       = "ensembl", 
+                                    organism = "Homo sapiens",
+                                    path     = "proteomes", 
+                                    release =  "release-97", 
+                                    gunzip = TRUE)
Starting proteome retrieval of 'Homo sapiens' from ensembl ...


错误: Please provide a release number that is supported by ENSEMBL.
```

**Comment by ShixiangWang** [comment]
After debugging, I find `release` should be an integer, however, `75` cannot work, but 97 works.

**Comment by ShixiangWang** [comment]
I find the reason, v75 uses GRCh37 while your query uses GRCh38. Maybe you should take some time to fix this issue.

![image](https://user-images.githubusercontent.com/25057508/65506033-39d71580-defd-11e9-83b8-7e113871913a.png)

**Comment by HajkD** [comment]
Hi @ShixiangWang 

Many thanks for making me aware of this issue. 

I will have a look at this and will come back to you soon.

Best wishes,
Hajk

**Comment by Roleren** [comment]
Have you fixed this yet, would be an easy fix with this ?

default_coord_system_version <- ifelse(version > 75, "GRCh38", "GRCh37")

I don't know if 75 is where the split was, but this could be applied backwards, want me to check it out and make a PR on it ?

**Comment by HajkD** [comment]
This would be amazing! Yes, please go ahead! Your help is truly appreciated!

**Comment by Roleren** [comment]
Ok, done. I see a lot of the tests still fail because of the SSL bug, but the primary once are fixed from their side now I think. I see you use curl instead of the newer RCurl in a lot the functions, curl is now pretty old and I tested to swap to RCurl and that fixes a lot of issues. 

But that should be improvement for later. 

Will send you pr now, this should work for all assemblies on ensembl down to release 46, downwards from there, they do not have a very good naming of files. But that should be fine, I will add a warning if people try to do less than 47, so that they are aware they won't get any results from that.

**Comment by Roleren** [comment]
https://github.com/ropensci/biomartr/pull/61

**Comment by Roleren** [comment]
Ok, good to go.

Now protein, DNA fasta and DNA gtf all can access ensembl releases correctly down to 46

**Comment by HajkD** [comment]
This is fantastic work, Håkon! Thank you so much for your help with this! Your pr is merged. 
Please also feel free to exchange `curl` for `RCurl` if it makes more sense and is more stable.
When I started the package ~5 years ago, `curl` was more robust, but I am happy to update towards
the state-of-the-art approach.

Many thanks,
Hajk
