### ISSUE TITLE
getRNA followed read_rna with wrong data type

### ISSUE THREAD

**Issue by AlexanderBartholomaeus** [ropensci/biomartr#46]
When using `getRNA()` followed by `read_rna()`, as shown in your example on the [getRNA help page](https://ropensci.github.io/biomartr/reference/getRNA.html) wrong data types are used. `read_rna` uses `RNAStringSet` but the downloaded sequences are in DNA format and thus `DNAStringSet` must be used. 

Here is an example similar to yours from the help page where all T's are ignored:
```
rnaFile <- getRNA(db='refseq', organism='49339')
read_rna(rnaFile)
```

The workaround is using read_genome instead, but I guess it makes more sense to correct the function.
```
rnaFile <- getRNA(db='refseq', organism='49339')
read_genome(rnaFile)
```

**Comment by HajkD** [comment]
Hi Alexander,

Many thanks for catching this bug!

I will fix this now by using `DNAStringSet` in `read_rna()`.

Thank you very much!

**Comment by AlexanderBartholomaeus** [comment]
Hi Hajk,

thank you for the very fast fix! 

Best regards,
Alex
