### ISSUE TITLE
Homo sapiens rsid to geneid

### ISSUE THREAD

**Issue by kokyriakidis** [ropensci/biomartr#49]
Hi! I am facing a timeout error when I try to annotate files containing significant rsids from a GWAS study and retrive the external_gene_id with BiomaRt. This is the command I use:
```
rslist_gene <- getLDS(attributes = c("refsnp_id"),
                          filters = "snp_filter",
                          values = rslist, #rslist is the list of rsids that I want to get the corresponding geneid
                          mart = snpdataset,
                          attributesL = c("external_gene_name"),
                          martL = genedataset)
```
Is there a way to achive something similar to this with your tool? I tried with this command with no luck
```
rslist_gene <- biomartr::biomart(genes      = rslist,
                                    mart       = c("ENSEMBL_MART_ENSEMBL", "ENSEMBL_MART_SN"),
                                    dataset    = c("hsapiens_gene_ensembl", "hsapiens_snp"),
                                    attributes = c("refsnp_id","external_gene_name"),
                                    filters    = "snp_filter")
```

**Comment by HajkD** [comment]
Hi Konstantinos,

Many thanks for contacting me.

Would it be possible to give me some more information?

Which `biomartr` version are you using (the dev version from GitHub)?

Have you tried to find the right mart, dataset, attribute, and filter combination
using the _organism specific retrieval information_ as stated here: https://docs.ropensci.org/biomartr/articles/Functional_Annotation.html#organism-specific-retrieval-of-information ?

Also, if you could provide some example IDs for the `value` argument, this would allow me to run this example and see what can be done.

Best wishes,
Hajk
