### ISSUE TITLE
server certificate verification failed

### ISSUE THREAD

**Issue by 276562578** [ropensci/biomartr#51]
the error show below when i run code
`ensembl <- useEnsembl(biomart = "ensembl", dataset = "hsapiens_gene_ensembl",mirror = "asia")`

`Error in curl::curl_fetch_memory(url, handle = handle) : 
  server certificate verification failed. CAfile: none CRLfile: none`

what should I do?

It's very appreciate your help!

**Comment by HajkD** [comment]
Could it be that you sit behind a firewall? From which asian country do you try to access the data?

**Comment by 276562578** [comment]
As what I know, I can access the http://asia.ensembl.org/ directly. And the code 
`ensembl <- useEnsembl(biomart = "ensembl", dataset = "hsapiens_gene_ensembl",mirror = "www")`
is work but slowly.
So what should I test or upload?

It's very appreciate your respond!

**Comment by HajkD** [comment]
There is nothing to upload. This is an API access to the ENSEMBL servers. To be honest, I am not quite sure what the issue is. There could be many reasons why your connection is slow. Which version of `biomartr` are you using?

**Comment by 276562578** [comment]
`biomaRT 2.42.1'
I think the problem may be caused by the `curl`? Seems lack `CA` file? But, there is nothing I can do to fix it.

**Comment by HajkD** [comment]
This could be the reason. Maybe you can also contact the authors of the `biomaRt` package since this package `biomartr` does extend the initial `biomaRt` functions, but does not host them.
