### ISSUE TITLE
getProteomeSet silently downloads wrong fasta file

### ISSUE THREAD

**Issue by AlexNesm** [ropensci/biomartr#52]
Hi! Thank you very much for biomartr, which saves a lot of time!
I encountered an issue. I tried to download five proteomes specifying organism names and assembly versions that I needed. Three times out of five I've got proteomes of Wolbachia symbionts instead of insects that I specified. For example, the following call:
`getProteomeSet(
    db = "refseq",
    organisms = "Drosophila melanogaster",
    release = "GCF_000001215.4")`
downloads the proteome of Wolbachia instead of Drosophila's.  

This issue can't be easily spotted from biomartr download summary, which provides incorrect organism name:

> File Name: Drosophila_melanogaster_protein.faa.gz
> Organism Name: Drosophila_melanogaster
> Database: NCBI refseq
> URL: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/008/025/GCF_000008025.1_ASM802v1/GCF_000008025.1_ASM802v1_protein.faa.gz
> Download_Date: Wed May 27 19:40:49 2020
> refseq_category: representative genome
> assembly_accession: GCF_000008025.1
> bioproject: PRJNA224116
> biosample: SAMN02604000
> taxid: 163164
> infraspecific_name: strain=wMel
> version_status: latest
> release_type: Major
> genome_rep: Full
> seq_rel_date: 2004-02-05
> submitter: TIGR

I revealed that there is some problem just by accident, noticing the implausibly small size of the downloaded fasta files.
I made sure that Drosophila assembly ID in the call to getProteomeSet is correct:
https://www.ncbi.nlm.nih.gov/assembly/GCF_000001215.4/
I know that biomartr is a tool for a batch download, but specifying both organism and assembly id I would rather expect to get the exact match.

**Comment by HajkD** [comment]
Hi Alex,

Many thanks for contacting me and for your kind feedback.

The `release` option only works for `ENSEMBL` databases and not for NCBI databases.

To retrieve the correct accession you could do:

```r
biomartr::getProteomeSet( db = "refseq", organisms = "GCF_000001215.4")
```

Also, as specified in the vignette (https://docs.ropensci.org/biomartr/articles/Sequence_Retrieval.html#example-ncbi-refseq-is-genome-available), the use of `is.genome.available()` should allow you to retrieve the right version of a species that was specified only by the scientific name:

```r
biomartr::is.genome.available(db = "refseq", organism = "Drosophila melanogaster", details = TRUE)
```
```
# A tibble: 5 x 21
  assembly_access… bioproject biosample wgs_master
  <chr>            <chr>      <chr>     <chr>     
1 GCF_000008025.1  PRJNA2241… SAMN0260… NA        
2 GCF_000001215.4  PRJNA164   SAMN0280… NA        
3 GCF_000884455.1  PRJNA4854… NA        NA        
4 GCF_000885235.1  PRJNA4854… NA        NA        
5 GCF_002815755.1  PRJNA4854… NA        NA        
# … with 17 more variables: refseq_category <chr>,
#   taxid <int>, species_taxid <int>,
#   organism_name <chr>, infraspecific_name <chr>,
#   isolate <chr>, version_status <chr>,
#   assembly_level <chr>, release_type <chr>,
#   genome_rep <chr>, seq_rel_date <date>,
#   asm_name <chr>, submitter <chr>,
#   gbrs_paired_asm <chr>, paired_asm_comp <chr>,
#   ftp_path <chr>, excluded_from_refseq <chr>
```

In any case, I will now implement an additional check so that users get an error message when they try to specify the `release` argument with non-ENSEMBL databases.

I hope this helps?

Many thanks,
Hajk

**Comment by AlexNesm** [comment]
Yes, such an additional check would be helpful! Thank you!
