### ISSUE TITLE
Checking existence of specific genome in getCollection function

### ISSUE THREAD

**Issue by TakahiroYamada** [ropensci/biomartr#53]
Hi Hello. I'm Takahiro Yamada and greatly thanks to you for very convenient R package, biomartr.
I tried to get a genome from NCBI GenBank database and faced following error.

```
> biomartr::getCollection(db = "genbank" , "GCA_900240375.1")
Starting collection retrieval (genome, proteome, cds, gff/gtf, rna, repeat masker, assembly stats) for GCA_900240375.1 ...
|===============================================================================| 100%   54 MB
Unfortunatey, no entry for 'GCA_900240375.1' was found in the 'refseq' database. Please consider specifying 'db = genbank' or 'db = ensembl' or 'db = ensemblgenomes' or 'db = uniprot' to check whether 'GCA_900240375.1' is available in these databases.
 error: No entry was found for organism GCA_900240375.1. Could the name be misspelled?
```

The species of this genome is registered in NCBI GenBank, and GenBank assembly accession is registered but RefSeq assembly accession is not (please see following URL).
https://www.ncbi.nlm.nih.gov/assembly/GCA_900240375.1

I suppose my error was generated because of the following code in getCollection.R,
```
getCollection <-
        function(db = "refseq",
                 organism,
                 reference = TRUE,
                 release = NULL,
                 gunzip = FALSE,
                 remove_annotation_outliers = FALSE,
                 path = file.path("_db_downloads","collections")
        ) {
        
        new_name <- stringr::str_replace_all(organism," ","_")
        message("Starting collection retrieval (genome, proteome, cds, gff/gtf, rna, repeat masker, assembly stats) for ", new_name, " ...")
            
        org_exists <- is.genome.available(db = "refseq", organism, details = TRUE) 
...
```
The above code `` org_exists <- is.genome.available(db = "refseq", organism, details = TRUE)`` may be `` org_exists <- is.genome.available(db = db, organism, details = TRUE)`` if genome should be checked based on user specified database?

I also confirmed ``is.genome.available(db = "genbank" , "GCA_900240375.1")`` generates ``TRUE``.

Thank you!

Takahiro

**Comment by HajkD** [comment]
Hi Takahiro,

Thank you so much for contacting me and absolutely brilliant that you caught this bug!
Thank you very much!

I already fixed this bug and the function should work accordingly now.

Thank you!

Hajk

**Comment by TakahiroYamada** [comment]
Great!
Thank you very much for your prompt fixing it!

Takahiro
