### ISSUE TITLE
how to download all bacterial genomes from specific phylum 

### ISSUE THREAD

**Issue by javadgh6** [ropensci/biomartr#54]
Hello,
How can I use biomartr package to download all genomes in a specific bacterial phylum  (for example Proteobacteria)??

**Comment by HajkD** [comment]
https://docs.ropensci.org/biomartr/articles/Sequence_Retrieval.html#retrieving-kingdom-group-and-subgroup-information

**Comment by javadgh6** [comment]
Hi, and thank you for your promote reply but which one must be used getGenomeSet() or getGenome()? how to define group? in tutorial it only have the organism = "??" option, but there is no group= "??" option. could you please write the command to retrieve all available genomes for "Proteobacteria" phylum  in refseq database. 
Thank you

**Comment by HajkD** [comment]
The documentation includes all information for this request.
