### ISSUE TITLE
Ensembl primary assembly

### ISSUE THREAD

**Issue by Roleren** [ropensci/biomartr#55]
Hey, thanks for the great package. 

Just a question, it looks like as default biomartr::getGenome for human (ensembl) gets the File:Homo_sapiens.GRCh38.dna.toplevel.fa.gz
which is huge! > 50GB uncompressed, and most people don't need infinite haplotypes. Is there a way we could specify to get primary assembly, the file: File:Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz . Which is much smaller and contains what most people need ? 

I checked zebrafish too, and it gives the dna.toplevel file > 50GB. 

Thanks. If you want to do this and need some help let me know.

**Comment by Roleren** [comment]
BTW, I found I could use internal function for this, so only thing you need to change is to export the id.type argument:

biomartr:::getENSEMBL.Seq("Homo sapiens", type = "dna", release = NULL,
id.type = "primary_assembly", path = "/data/references/test_human")

So the function would look like this: 
biomartr::getGenome(db = "ensembl", organism = "Homo sapiens", id.type = "primary_assembly", path = "/data/references/test_human")

**Comment by HajkD** [comment]
Hi Håkon,

This is a brilliant suggestion! Thank you very much!

I will see how to elegantly add the `id.type` argument to the `getGenome()` function. 
Since the `NCBI` API functions don't have this argument, I have to make sure not to confuse users.

But I am happy to think about a solution!

Many thanks!
Hajk

**Comment by Roleren** [comment]
Yes, true. It is a easy fix, add a assembly.version argument to biomartr::getGenome and update the id.type = "toplevel" to id.type = assembly.version.


By the way this line id.type = "toplevel" is found 2 places, one when db is "ensembl" but also when db is "ensemblgenomes"

But "ensemblgenomes" is not a valid input for db argument, so don't quite get that one.  

You want me to send a Pull request with it ?

**Comment by HajkD** [comment]
Hi Håkon,

if it isn't too much trouble for you then it would be fantastic if you could implement this new feature and send me a pull request.

Would it in that case be possible to write a small update statement in the [NEWS](https://github.com/ropensci/biomartr/blob/master/NEWS.md) file and a small tutorial of the new functionality in the [Sequence Retrieval Vignette](https://github.com/ropensci/biomartr/blob/master/vignettes/Sequence_Retrieval.Rmd)?

Your help with improving `biomartr` is very much appreciated!

Many thanks,
Hajk

**Comment by Roleren** [comment]
Should have it done before Friday.

**Comment by HajkD** [comment]
Absolutely brilliant!
Thank you very much!!!

**Comment by Roleren** [comment]
PR ready: 
`https://github.com/ropensci/biomartr/pull/56`
