### ISSUE TITLE
read_cds fails when returning in data.table format

### ISSUE THREAD

**Issue by clementfkent** [ropensci/biomartr#57]
installed biomartr today. read_cds(file="testCDS.txt",format = "fasta", obj.type = "data.table") fails with message:
"Error: File testCDS.txt could not be read properly. 
Please make sure that testCDS.txt contains only CDS sequences and is in fasta format."

testCDS.txt and a revised version of read_cds are attached. Revised version works well. NB: 
[read_cds2.txt](https://github.com/ropensci/biomartr/files/4978067/read_cds2.txt)
This file only contains the code for the data.table case - I didn't test the Biostrings case

[testCDS.txt](https://github.com/ropensci/biomartr/files/4978064/testCDS.txt)

**Comment by HajkD** [comment]
Hi Clement,

Many thanks for making me aware of this issue. To be honest I wanted to depreciate the `data.table` feature of `read_cds()`.
Do you find it more useful than the `Biostrings` version for your application? If yes, then I will have a deeper look into it and will fix any issues that may exist in the current version.

Many thanks,
Hajk

**Comment by clementfkent** [comment]
Thanks for the reply, Hajk. I just began using the package recently. My R
code is very datatable and dataframe based, so I am most comfortable with
that side of it.

Cheers,
Clement



*Clement Kent, Ph.D.*
*Adjunct Professor, Dept. of Biology*
*York University, Canada*

**Comment by HajkD** [comment]
Dear Clement,

Excellent. In that case I will have a look into it and will make sure that this feature functions smoothly.

Many thanks for your feedback.

Cheers,
Hajk

**Comment by HajkD** [comment]
Dear Clement,

I found the issue and fixed it. In addition, I added a more extensive check for CDS sequences that have lengths that do not divide by 3 (which sadly exists quite frequently in NCBI/ENSEMBL datasets).

Many thanks for pointing this issue out to me and I hope that the function works for you now.

```r
biomartr::read_cds(file = "testCDS.txt", obj.type = "data.table", delete_corrupt = TRUE)
```

Best wishes,
Hajk
