### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by limfs92** [ropensci/biomartr#59]
Hi,

I am just starting to use the package and am relatively new to this. I wished to download bacterial, fungi and viral database from NCBI RefSeq. I came across this problem (please see below) after going through the tutorial as listed on the page.

_> is.genome.available(db = "refseq", organism = "Homo sapiens")
trying URL 'ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/archaea/assembly_summary.txt'
Something went wrong when trying to access the FTP site 'ftp://ftp.ncbi.nlm.nih.gov/'. Sometimes the internet connection isn't stable and re-running the function might help. Otherwise, could there be an issue with the firewall?. Is the the FTP site 'ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/archaea/assembly_summary.txt' currently available?
Error: '/tmp/RtmpCFtdOg/assembly_summary_archaea_refseq.txt' does not exist.
In addition: Warning message:
In download.file(url, ...) :
  URL 'ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/archaea/assembly_summary.txt': status was 'Couldn't connect to server'_

I would greatly appreciate any sort of help. Thank you in advance!

**Comment by HajkD** [comment]
Hi,

I assume you checked that you have internet access through the server you try to connect from and are not blocked by a firewall?

Cheers

**Comment by limfs92** [comment]
Hi @HajkD ,

After several check with our IT department, we realized that the internet access is blocking the access to server due to security reason and thus resulting in the issue mentioned above. Thank you for your suggestion.

Best,
Lim
