### ISSUE TITLE
one same ensembl ID gets multiple entrez IDs with same gene symbol

### ISSUE THREAD

**Issue by amssljc** [ropensci/biomartr#62]
Hi, I am a fresh user of 'biomaRt'.
when, I use your package, I found that multiple entrez IDs can map to one same ensembl ID.
And I'm confused about that, which entrezID should I use?
this is my code:
```
library('biomaRt')
mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
G_list <-
  getBM(
    filters = "ensembl_gene_id",
    attributes = c("ensembl_gene_id",
                   "hgnc_symbol",
                   'entrezgene_id'),
    values = as.character(gene.IDs),
    mart = mart
  )
```

and the variable 'gene.IDs' is my ensembl IDs.

this is the part of result:
```
...
7575	ENSG00000137822	TUBGCP4	27229
7576	ENSG00000137824	RMDN3	55177
7577	ENSG00000137825	ITPKA	3706
7578	ENSG00000137831	UACA	55075
7579	ENSG00000137834	SMAD6	4091
7580	ENSG00000137841	PLCB2	5330
7581	ENSG00000137842	TMEM62	80021
7582	ENSG00000137843	PAK6	56924
7583	ENSG00000137843	PAK6	106821730
7584	ENSG00000137845	ADAM10	102
7585	ENSG00000137857	DUOX1	53905
...
```

As you can see, the 7582 and 7583 rows return the same ensembl IDs and gene symbols but with different entrez IDs.
After my search on NCBI, I found 56924 is direct for gene 'PAK6', and 106821730 is called 'BUB1B-PAK6' which also known as 'PAK6'. 

And I want to ask which one should I use for further research?
Or I think at least, the returned 'hgnc_symbol' should have a differece, but both results returned 'PAK6'. Maybe 'BUB1B-PAK6' in the 7583-th row and with entrezID '106821730' is a better choise.

Thanks a lot if you can reply for me!

**Comment by HajkD** [comment]
Hi @amssljc,

As this is the [biomartr](https://github.com/ropensci/biomartr#similar-work) package and not the `biomaRt` package, did you have a chance to have look here and check if the organism specific query notation of `biomartr` can help you to resolve this issue: https://docs.ropensci.org/biomartr/articles/Functional_Annotation.html? 

In addition, if this is a mis-entry in the Ensembl BioMart dataset, then it would be best to contact the Ensembl mailing list.

I hope this helps!

Cheers,
Hajk
