### ISSUE TITLE
there is no package called ‘biomartr’

### ISSUE THREAD

**Issue by iquasere** [ropensci/biomartr#64]
Greetings

I have installed biomartr with ```conda install -c bioconda r-biomartr``` but when trying to load the package in R with ```library('biomartr')``` it gives me
```
Error in library("biomartr") : there is no package called ‘biomartr’
```
How should I load biomartr?

**Comment by iquasere** [comment]
Ok, this was a new one for me. ```R``` doesn't call the env R, but rather the one at ```anaconda3/bin```. Running the env R explicitly with ```anaconda3/envs/proteomics/bin/R``` fixes this

**Comment by HajkD** [comment]
Excellent! :-)
