### ISSUE TITLE
Can I download proteomes of upper taxonomic levels?

### ISSUE THREAD

**Issue by iquasere** [ropensci/biomartr#65]
For example, if I wanted all proteomes of Archaea, could I do that with biomartr? I have tried getting all for the Methanobacteriales order, but it only gets me proteomes for uncharacterized Methanobacteriales that don't have a real name yet. Does this only work with species names?

**Comment by HajkD** [comment]
Do I assume correctly that you have tried this: https://docs.ropensci.org/biomartr/articles/MetaGenome_Retrieval.html#retrieve-groups-or-subgroups-of-species ?

**Comment by iquasere** [comment]
Yes, I had already tried with meta.retrieval, but it does not allow "uniprot" as a database. Besides, the example you put only seems to allow for the retrieval of different phyla, and not of orders, for example

**Comment by iquasere** [comment]
Well, I found it is easy through [direct download](https://www.biostars.org/p/476933/). Thank you for your attention! ^^

**Comment by HajkD** [comment]
Brilliant! Unfortunately, for `UniProt` I didn't have this feature implemented yet, but thanks to the solution that you found it might not be that time consuming to add this feature in the future. Many thanks!
