### ISSUE TITLE
Using taxid for genome retrieval does not work for any species or strain

### ISSUE THREAD

**Issue by raphaelajoos** [ropensci/biomartr#71]
Hi Hajk, 

thanks for the amazing package, very helpful. 

I am trying to curate a reference db for all Lactobacillaceae species but are running into several problems, without
any success fixing them. 

First of all, the taxid and the species names for genome retrieval always gives me an error message saying:

Unfortunately no genome file could be found for organism 'Lactobacillus alvei'. Thus, the download of this organism has been omitted. Have you tried to specify 'reference = FALSE' ?

I did specify the reference but it's still the same error. Furthermore, when downloading genomes I always receive this message:

the download session seems to have timed out at the FTP site 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/191/545/GCF_000191545.1_ASM19154v1/GCF_000191545.1_ASM19154v1_genomic.fna.gz'. This could be due to an overload of queries to the databases. Please restart this function to continue the data retrieval process or wait for a while before restarting this function in case your IP address was logged due to an query overload on the server side.
Error: Please provide a valid file path to your genome assembly file.

sometimes a rerun solves the problem but mostly it doesn't. 

Do you have any advice for me in terms of how to go from here? When checking the NCBI website it says there are over 6000 reference genomes available for Lactobacillaceae, however I do not seem to be able to download any. 

Hope you can help. 

Best, 
Rapha

**Comment by HajkD** [comment]
Hi Rapha,

Many thanks for your feedback!

Could the default timeout limit of 60s explain this issue?

You can reset the timeout limit via:

```r
options(timeout = 30000)
```

For example, the NCBI species summary file for bacteria is >300MB and with a slow connection the 60sec timeout limit is easily reached.

If you now install the developer version of `biomartr`, the timeout limit is now internally handled and set to 30000 by default.

Does this help?

Cheers,
Hajk

**Comment by Roleren** [comment]
I believe either an old URL problem or simply wrong naming was the problem here, 
I can confirm this now works:

`getGenome(db = "refseq", organism = "Loigolactobacillus backii", mute_citation = TRUE, path = tempdir())`

returns valid output

This issue can now be closed.

**Comment by HajkD** [comment]
Thank you very much for double-checking and confirming, @Roleren!
