### ISSUE TITLE
errors in getGO

### ISSUE THREAD

**Issue by rocpengliu** [ropensci/biomartr#74]
Hi Biomartr

I have an error when i run the following command

GO_tbl <- biomartr::getGO(organism = "Coturnix japonica", 
                          genes    = "107309205",
                          filters  = "entrezgene_id");

Error in biomartr::getGO(organism = "Coturnix japonica", genes = "107309205",  : 
  GO related attributes have been found in more than one mart or 
            dataset: mart = ENSEMBL_MART_ENSEMBL ; dataset = cjaponica_eg_genecjaponica_gene_ensembl

I don't see the error when I run the organism of chicken

Any idea about this

Thank you so much!

Peng

**Comment by HajkD** [comment]
I get the error message:
`GO related attributes have been found in more than one mart or 
            dataset: mart = ENSEMBL_MART_ENSEMBL ; dataset = cjaponica_eg_genecjaponica_gene_ensembl`

Does this help to resolve your issue?

Best wishes,
Hajk

**Comment by HajkD** [comment]
I assume this is resolved.
