### ISSUE TITLE
Lock error in 4.1.1 not in 4.03

### ISSUE THREAD

**Issue by ZheFrench** [ropensci/biomartr#80]
I removed the directory and reinstall biomartR several times. Didn't work. Any idea would be more than welcome.

> Erreur dans lock(.sql_lock_path(dbfile)) : 
>   Cannot lock file: '/home/villemin/.cache/biomaRt/BiocFileCache.sqlite.LOCK': Aucun verrou disponible
> Appels : getBM ... tryCatch -> tryCatchList -> .sql_connect_RW -> lock
> Erreur dans h(simpleError(msg, call)) : 
>   erreur d'ï¿½valuation de l'argument 'conn' lors de la sï¿½lection d'une mï¿½thode pour la fonction 'dbDisconnect' : objet 'info' introuvable
> Appels : getBM ... .sql_disconnect -> dbDisconnect -> .handleSimpleError -> h
> 

> R version 4.1.1 (2021-08-10)
> Platform: x86_64-conda-linux-gnu (64-bit)
> Running under: Ubuntu 18.04.6 LTS
> 
> Matrix products: default
> BLAS/LAPACK: /data/USERS/villemin/anaconda3/envs/r4.1/lib/libopenblasp-r0.3.17.so
> 
> locale:
>  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
>  [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
>  [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats4    parallel  stats     graphics  grDevices utils     datasets 
> [8] methods   base     
> 
> other attached packages:
>  [1] optparse_1.7.1         plyr_1.8.6             biomaRt_2.48.3        
>  [4] GenomicFeatures_1.44.2 AnnotationDbi_1.54.1   Biobase_2.52.0        
>  [7] GenomicRanges_1.44.0   GenomeInfoDb_1.28.4    IRanges_2.26.0        
> [10] S4Vectors_0.30.2       BiocGenerics_0.38.0    reshape2_1.4.4        
> [13] data.table_1.14.2     
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.8                  lattice_0.20-45            
>  [3] prettyunits_1.1.1           png_0.1-7                  
>  [5] Rsamtools_2.8.0             Biostrings_2.60.2          
>  [7] assertthat_0.2.1            digest_0.6.29              
>  [9] utf8_1.2.2                  BiocFileCache_2.0.0        
> [11] R6_2.5.1                    RSQLite_2.2.9              
> [13] httr_1.4.2                  pillar_1.7.0               
> [15] zlibbioc_1.38.0             rlang_1.0.1                
> [17] progress_1.2.2              curl_4.3.2                 
> [19] blob_1.2.2                  Matrix_1.4-0               
> [21] BiocParallel_1.26.2         stringr_1.4.0              
> [23] RCurl_1.98-1.6              bit_4.0.4                  
> [25] DelayedArray_0.18.0         compiler_4.1.1             
> [27] rtracklayer_1.52.1          pkgconfig_2.0.3            
> [29] SummarizedExperiment_1.22.0 tidyselect_1.1.1           
> [31] KEGGREST_1.32.0             tibble_3.1.6               
> [33] GenomeInfoDbData_1.2.6      matrixStats_0.61.0         
> [35] XML_3.99-0.7                fansi_1.0.2                
> [37] crayon_1.5.0                dplyr_1.0.8                
> [39] dbplyr_2.1.1                GenomicAlignments_1.28.0   
> [41] bitops_1.0-7                rappdirs_0.3.3             
> [43] grid_4.1.1                  lifecycle_1.0.1            
> [45] DBI_1.1.2                   magrittr_2.0.2             
> [47] cli_3.2.0                   stringi_1.7.4              
> [49] cachem_1.0.6                XVector_0.32.0             
> [51] getopt_1.20.3               xml2_1.3.3                 
> [53] ellipsis_0.3.2              filelock_1.0.2             
> [55] generics_0.1.2              vctrs_0.3.8                
> [57] rjson_0.2.21                restfulr_0.0.13            
> [59] tools_4.1.1                 bit64_4.0.5                
> [61] glue_1.6.1                  purrr_0.3.4                
> [63] MatrixGenerics_1.4.3        hms_1.1.1                  
> [65] fastmap_1.1.0               yaml_2.2.2                 
> [67] memoise_2.0.1               BiocIO_1.2.0               

By the way, It works with this environment.

> R version 4.0.3 (2020-10-10)
> Platform: x86_64-conda-linux-gnu (64-bit)
> Running under: Ubuntu 18.04.6 LTS
> 
> Matrix products: default
> BLAS/LAPACK: /data/USERS/villemin/anaconda3/envs/r4-base/lib/libopenblasp-r0.3.12.so
> 
> locale:
>  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
>  [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
>  [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats4    parallel  stats     graphics  grDevices utils     datasets 
> [8] methods   base     
> 
> other attached packages:
>  [1] optparse_1.6.6         plyr_1.8.6             biomaRt_2.46.3        
>  [4] GenomicFeatures_1.42.3 AnnotationDbi_1.52.0   Biobase_2.50.0        
>  [7] GenomicRanges_1.42.0   GenomeInfoDb_1.26.7    IRanges_2.24.1        
> [10] S4Vectors_0.28.1       BiocGenerics_0.36.0    reshape2_1.4.4        
> [13] data.table_1.14.0     
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.7                  lattice_0.20-44            
>  [3] prettyunits_1.1.1           Rsamtools_2.6.0            
>  [5] Biostrings_2.58.0           assertthat_0.2.1           
>  [7] utf8_1.2.1                  BiocFileCache_1.14.0       
>  [9] R6_2.5.1                    RSQLite_2.2.5              
> [11] httr_1.4.2                  pillar_1.7.0               
> [13] zlibbioc_1.36.0             rlang_1.0.1                
> [15] progress_1.2.2              curl_4.3                   
> [17] rstudioapi_0.13             blob_1.2.1                 
> [19] Matrix_1.3-4                BiocParallel_1.24.1        
> [21] stringr_1.4.0               RCurl_1.98-1.3             
> [23] bit_4.0.4                   DelayedArray_0.16.3        
> [25] compiler_4.0.3              rtracklayer_1.50.0         
> [27] pkgconfig_2.0.3             askpass_1.1                
> [29] openssl_1.4.3               tidyselect_1.1.1           
> [31] SummarizedExperiment_1.20.0 tibble_3.1.6               
> [33] GenomeInfoDbData_1.2.4      matrixStats_0.58.0         
> [35] XML_3.99-0.6                fansi_0.4.2                
> [37] crayon_1.4.1                dplyr_1.0.7                
> [39] dbplyr_2.1.0                GenomicAlignments_1.26.0   
> [41] bitops_1.0-6                rappdirs_0.3.3             
> [43] grid_4.0.3                  lifecycle_1.0.1            
> [45] DBI_1.1.1                   magrittr_2.0.2             
> [47] cli_3.2.0                   stringi_1.5.3              
> [49] cachem_1.0.4                XVector_0.30.0             
> [51] getopt_1.20.3               xml2_1.3.2                 
> [53] ellipsis_0.3.2              generics_0.1.0             
> [55] vctrs_0.3.8                 tools_4.0.3                
> [57] bit64_4.0.5                 glue_1.6.1                 
> [59] purrr_0.3.4                 hms_1.0.0                  
> [61] MatrixGenerics_1.2.1        fastmap_1.1.0              
> [63] memoise_2.0.0

**Comment by HajkD** [comment]
Are you using the developer version of the `biomartr` package?

Your error messages seem to have issues with the `biomaRt` package and not with the `biomartr` package itself, correct?

`Cannot lock file: '/home/villemin/.cache/biomaRt/BiocFileCache.sqlite.LOCK': Aucun verrou disponible`

Here you can find infos about the [differences between biomaRt and biomartr](https://github.com/ropensci/biomartr#similar-work).

Cheers,
Hajk

**Comment by ZheFrench** [comment]
Ahah True. My bad.
Thanks.
