### ISSUE TITLE
Download of genomes fails when release number and/or assembly type are provided

### ISSUE THREAD

**Issue by vizkidd** [ropensci/biomartr#83]
For Ensembl : release version 107, Assembly types : toplevel, primary_assembly
Steps to reproduce :
Just give a db="ensembl", release=107 and assembly_type="primary_assembly" when invoking getGenome()

Error Produced: Found organism but given release number did not specify existing file 

It works fine when these options are not included and the download works properly

**Comment by vizkidd** [comment]
Forgot to mention,

R version : Both 4.1.1 and 4.2.1

**Comment by vizkidd** [comment]
![biomartr_issue](https://user-images.githubusercontent.com/8852055/187175209-9d1daf3c-1f35-40f0-a384-be13c2ee8244.png)

Update: There are several organisms which fail and several which work, sus_scrofa doesn't seem to work even though the genome is listed and available through the function is.genome.available()

**Comment by HajkD** [comment]
Dear Vishvesh,

Many thanks for notifying me. 

I can have a look and see if a patch can be provided. 

Cheers,
Hajk

**Comment by Roleren** [comment]
Hello, simple answer is that there is no primary assembly for the whole pig genome.

Usually when I use biomartr for this, I make a tryCatch and start with primary, if it fails then I try top-level.

This question can be closed

**Comment by HajkD** [comment]
Excellent!!! Thank you so much for your inisght!
