### ISSUE TITLE
Listing and downloading all proteomes from Ensembl Plants/Fungi/Protists

### ISSUE THREAD

**Issue by almeidasilvaf** [ropensci/biomartr#84]
Hi, @HajkD 

Thank you for this very nice package. 

I saw that EnsemblGenomes was retired in 2019. Does that mean that it is not possible to list and download genomes/proteomes from EnsemblPlants, EnsemblFungi and EnsemblProtists with this package?

That seems strange, because I can query these databases with biomaRt and download sequences with `getSequence()`. The problem with biomaRt is that I have to get all gene IDs first, and then use them to obtain the sequences, but that seems like an ugly solution, so I thought biomartr could have a function to obtain the proteomes in a single line of code.

Did I get anything wrong?

Best,
Fabricio

**Comment by Roleren** [comment]
A new update with support for this will come in not too long.

**Comment by Roleren** [comment]
This now works, an example is:

```
getProteome(
    db       = "ensembl",
    organism = "Escherichia coli",
    path     = tempdir(), mute_citation = TRUE
  )
```
  
  The issue can now be closed

**Comment by HajkD** [comment]
Excellent! Thank you very much for fixing this issue!
