### ISSUE TITLE
Retrieve genes from a locus by knowing the chromosome position 

### ISSUE THREAD

**Issue by zh-zhang1984** [ropensci/biomartr#85]
Dear authors, 
I encounter this package and find it can be helpful for my purpose: Retrieve genes from a locus by knowing the chromosome position. 
I have the information like:
```
> loci
    LOC CHR     START      STOP
1     1   1     10539   1376204
2     2   1   1376205   2215495
3     3   1   2215496   2983519
4     4   1   2983520   3582047
5     5   1   3582048   4281476
6     6   1   4281477   4773403
7     7   1   4773404   5362404
8     8   1   5362405   6136814
9     9   1   6136815   7711794
```
I want to retrieve gene names for each locus; is there any hints on how to do this with the [biomartr] (https://github.com/ropensci/biomartr) package? 
Thank you very much for your help.
Public

**Comment by HajkD** [comment]
Hi,

No this feature is not implemented in `biomartr`. I guess what you would need to do is
to use `bedtools` to overlap coordinates with an annotation file (e.g. bed from gff3) to get the GeneIDs.

These GeneIDs you can then use to retrieve further annotation information with the [biomartr::biomart()](https://docs.ropensci.org/biomartr/articles/Functional_Annotation.html) function.

Cheers,
Hajk
