### ISSUE TITLE
Downloads not working; setup on windows?

### ISSUE THREAD

**Issue by raydioactive** [ropensci/biomartr#86]
Hi, thanks for this awesome package.
I'm trying to use it to download things; however, and while the assembly summaries download, I can't do any sort of actual retrievals. I suspect this to be due to my Windows 10 running laptop, as the code I've run works on a mac. I can't just buy a new laptop, how do I need to have my computer set up to allow this package to work? I've tried everything I can find and think of so far. What prevents it from working on windows?
``
> getGenome(
+   db = "refseq",
+   7227,
+   reference = FALSE,
+   release = NULL,
+   gunzip = FALSE,
+   path = file.path("_ncbi_downloads", "genomes"),
+ )
Starting genome retrieval of '7227' from refseq ...

The download session seems to have timed out at the FTP site 'https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/215/GCF_000001215.4_Release_6_plus_ISO1_MT/GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.fna.gz'. This could be due to an overload of queries to the databases. Please restart this function to continue the data retrieval process or wait for a while before restarting this function in case your IP address was logged due to an query overload on the server side.
Error: Please provide a valid file path to your genome assembly file.     
``

**Comment by babinecha** [comment]
Hi,

Did you fix the issue?

**Comment by HajkD** [comment]
Hi @babinecha 

I am glad to hear that you find `biomartr` useful for your research.

Unfortunately, `biomartr` was never developed for `Windows` systems and I can only assume that some of the retrieval checks are based on package dependencies that were also not built for `Windows`. 

I could treat this as a feature request to check whether `Windows` compatibility is achievable in the future and will put it on my long TODO list.

I hope this clarifies.

Best wishes,
Hajk

**Comment by babinecha** [comment]
Thanks for the clarification!
I hope I can use the package in the future, because it seems to be great.

**Comment by Roleren** [comment]
For now you can install R through WSL (windows subsystem for linux) and it will work for you there
