### ISSUE TITLE
getENSEMBL.Seq: Found organism but given release number did not specify existing file in ensembl...

### ISSUE THREAD

**Issue by ibphuangchen** [ropensci/biomartr#87]
Hey there:

```r
biomartr:::getENSEMBL.Seq(organism, type = "dna", release = NULL, 
                          id.type = "primary_assembly", 
                          path = '~')
```
gives the error:

**Found organism but given release number did not specify existing file                                                                  
                     in ensembl, maybe it is too old? Check that it exists on ensembl
                     first at all.**

any ideas? I'm using v1.0.2

**Comment by Roleren** [comment]
Hey there, this issue was related to a change in Curl library, was not actually biomartr, I have already made a PR and it is merged, download latest here and it should now work

**Comment by HajkD** [comment]
Fantastic!!!
