### ISSUE TITLE
Assembly summary txt download failed;  Something went wrong when trying to access the FTP site

### ISSUE THREAD

**Issue by xl0418** [ropensci/biomartr#90]
Hi, thanks for the package. It is very useful.

Everything goes well except when I tried to download the summary for bacteria from genbank.

ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/bacteria/assembly_summary.txt 

It says that 

`Something went wrong when trying to access the FTP site 'ftp://ftp.ncbi.nlm.nih.gov/'. Sometimes the internet connection isn't stable and re-running the function might help. Otherwise, could there be an issue with the firewall?. Is the the FTP site 'ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/bacteria/assembly_summary.txt' currently available?`

However, this link can be open from the browser. Without this summary, all genome of bacteria from genbank cannot be downloaed. 

BTW, this file has a size of nearly 500 mb, which is the biggest one among all summary files. Any clue if this causes some query problem?

So, I am wondering if you can help me with that. All other summary files can be downloaded, so it is unlikely to be due to the internet connection problem. 

I also wonder if I can downloaed these summary manually and put them in one folder. As such, everything we run the pkg, we donot need to download again.

Thanks and expect for your reply!

**Comment by Roleren** [comment]
Hello, the summaries fetching is not working properly in this version, I am planning a PR for my fork soon. 

For now I have fixed the problem (only for ensemble bacteria assembly summary for now).

Take a look here: 
https://github.com/Roleren/biomartr

**Comment by Roleren** [comment]
This is now fixed, the issue can be closed
