### ISSUE TITLE
specific genes/features from list of refseqs

### ISSUE THREAD

**Issue by omarkr8** [ropensci/biomartr#91]
Im trying to get nucleotide sequences for genes for several viruses of the same family.

let's say that on ncbi, each one is labelled as "mat_peptide" on the feature table, and product = "nonstructural protein NS3".
is there a way to use biomartr for this? i want to end up with either a multi-fasta or individual fastas of this gene for each refseq on a list.

alternatively, if anyone knows how to do this on other software that would be cool too.

**Comment by Roleren** [comment]
So two ways:

1. Download genome and gffs and extract regions of interest (this is more comprehensive, but complete solution)
2. Download only a subset of genome (transcript RNA sequences or CDS sequences)

So what do you want ?

**Comment by HajkD** [comment]
Thanks @Roleren 

I would add that for `2. Download only a subset of genome (transcript RNA sequences or CDS sequences)` the initial [biomaRt](https://bioconductor.org/packages/release/bioc/html/biomaRt.html) package would be the best go-to solution. 

For `1. Download genome and gffs and extract regions of interest (this is more comprehensive, but complete solution)`, we would need to implement a new function from scratch. 

Many thanks for this discussion!

Cheers,
Hajk

**Comment by Roleren** [comment]
For 1 I would use Bioconductor functions, and I don't think we should have it in biomartr.

This is very standardized with the txdb format in bioconductor,

for reference for how I usually do this combined with biomartr, see my package ORFik:

See section 3 of my [data import tutorial](https://bioconductor.org/packages/devel/bioc/vignettes/ORFik/inst/doc/Importing_Data.html#loading-gene-annotation-txdb):

**Comment by HajkD** [comment]
Sounds good to me!
